/**
 * Registro único de iconos del ERP — fuente: Phosphor Icons (@phosphor-icons/react).
 *
 * Toda pantalla importa sus iconos DESDE AQUÍ, nunca directo de la librería:
 *
 *     import { Printer, Truck } from '../../components/ui/icons';
 *
 * Los nombres exportados son los que el ERP usaba con lucide-react (migración
 * 2026-09-25, rediseño visual "Cristal y Aluminio"), así el cambio de librería no
 * tocó el JSX de ninguna pantalla. Cambiar un icono o la librería entera es
 * editar este archivo, no 129.
 *
 * Tamaño y peso por defecto los fija <IconContext.Provider> en app/App.tsx
 * (24px como lucide, para no mover layouts; peso 'bold', legible a 12–16px). Una
 * pantalla puede pedir otro peso con la prop `weight`: 'duotone' para iconos
 * protagonistas (menú, tarjetas de indicadores, estados vacíos), 'regular' para
 * iconos grandes (≥ 32px), 'fill' para marcar un estado activo.
 *
 * Para agregar un icono: buscarlo en https://phosphoricons.com, importar su
 * variante con sufijo `Icon` y exportarlo con un nombre descriptivo.
 */
import {
    ArchiveIcon,
    ArrowClockwiseIcon,
    ArrowCounterClockwiseIcon,
    ArrowDownIcon,
    ArrowElbowDownLeftIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowSquareOutIcon,
    ArrowUUpLeftIcon,
    ArrowUpIcon,
    ArrowsClockwiseIcon,
    BankIcon,
    BellIcon,
    BellSlashIcon,
    BookOpenIcon,
    BriefcaseIcon,
    BrowserIcon,
    BuildingIcon,
    BuildingsIcon,
    CalculatorIcon,
    CalendarBlankIcon,
    CalendarCheckIcon,
    CalendarDotsIcon,
    CameraIcon,
    CaretDownIcon,
    CaretLeftIcon,
    CaretRightIcon,
    CaretUpIcon,
    CaretUpDownIcon,
    ChartBarIcon,
    ChatCircleIcon,
    ChatTextIcon,
    CheckIcon,
    CheckCircleIcon,
    CheckSquareIcon,
    ChecksIcon,
    CircleIcon,
    CircleNotchIcon,
    ClipboardTextIcon,
    ClockIcon,
    ClockCounterClockwiseIcon,
    CloudIcon,
    CloudArrowUpIcon,
    CopyIcon,
    CpuIcon,
    CreditCardIcon,
    CrosshairIcon,
    CubeIcon,
    CurrencyDollarIcon,
    DatabaseIcon,
    DiamondIcon,
    DoorIcon,
    DoorOpenIcon,
    DotsSixVerticalIcon,
    DotsThreeVerticalIcon,
    DownloadSimpleIcon,
    DropIcon,
    EnvelopeIcon,
    EyeIcon,
    EyeSlashIcon,
    FactoryIcon,
    FileArrowDownIcon,
    FileCodeIcon,
    FilePlusIcon,
    FileTextIcon,
    FileXlsIcon,
    FileZipIcon,
    FilmStripIcon,
    FlagIcon,
    FlameIcon,
    FloppyDiskIcon,
    FrameCornersIcon,
    FunnelIcon,
    GaugeIcon,
    GearSixIcon,
    GitDiffIcon,
    HardDriveIcon,
    HardHatIcon,
    HashIcon,
    HourglassIcon,
    ImageIcon,
    ImageBrokenIcon,
    ImagesIcon,
    InfoIcon,
    KanbanIcon,
    LightbulbIcon,
    LightningIcon,
    LinkSimpleIcon,
    ListIcon,
    ListChecksIcon,
    ListDashesIcon,
    ListPlusIcon,
    LockIcon,
    MagicWandIcon,
    MagnifyingGlassIcon,
    MagnifyingGlassPlusIcon,
    MapPinIcon,
    MedalIcon,
    MinusIcon,
    MoneyIcon,
    NoteIcon,
    NotebookIcon,
    PackageIcon,
    PaperPlaneTiltIcon,
    PathIcon,
    PauseIcon,
    PauseCircleIcon,
    PenNibIcon,
    PencilLineIcon,
    PencilRulerIcon,
    PencilSimpleIcon,
    PencilSimpleLineIcon,
    PercentIcon,
    PhoneIcon,
    PhoneCallIcon,
    PhoneXIcon,
    PlayIcon,
    PlusIcon,
    PlusCircleIcon,
    PrinterIcon,
    ProhibitIcon,
    PulseIcon,
    QrCodeIcon,
    QuestionIcon,
    ReceiptIcon,
    RobotIcon,
    RulerIcon,
    ScalesIcon,
    ScanIcon,
    ScissorsIcon,
    ShieldIcon,
    ShieldCheckIcon,
    ShieldWarningIcon,
    ShoppingCartIcon,
    SignInIcon,
    SignOutIcon,
    SignatureIcon,
    SlidersIcon,
    SlidersHorizontalIcon,
    SnowflakeIcon,
    SparkleIcon,
    SquareIcon,
    SquaresFourIcon,
    StackIcon,
    StarIcon,
    SwapIcon,
    TableIcon,
    TagIcon,
    TargetIcon,
    TextAlignLeftIcon,
    TimerIcon,
    TrashIcon,
    TrayIcon,
    TreeStructureIcon,
    TrendDownIcon,
    TrendUpIcon,
    TrophyIcon,
    TruckIcon,
    UploadSimpleIcon,
    UserIcon,
    UserCheckIcon,
    UserCircleIcon,
    UserMinusIcon,
    UserPlusIcon,
    UsersIcon,
    WalletIcon,
    WarehouseIcon,
    WarningIcon,
    WarningCircleIcon,
    WarningOctagonIcon,
    WifiHighIcon,
    WifiSlashIcon,
    WrenchIcon,
    XIcon,
    XCircleIcon,
} from '@phosphor-icons/react';

export type { Icon as IconComponent, IconProps, IconWeight } from '@phosphor-icons/react';
export { IconContext } from '@phosphor-icons/react';

export {
    PulseIcon as Activity,
    WarningCircleIcon as AlertCircle,
    WarningOctagonIcon as AlertOctagon,
    WarningIcon as AlertTriangle,
    TextAlignLeftIcon as AlignLeft,
    ArchiveIcon as Archive,
    ArrowDownIcon as ArrowDown,
    ArrowLeftIcon as ArrowLeft,
    ArrowRightIcon as ArrowRight,
    ArrowUpIcon as ArrowUp,
    MedalIcon as Award,
    ProhibitIcon as Ban,
    MoneyIcon as Banknote,
    ChartBarIcon as BarChart2,
    ChartBarIcon as BarChart3,
    BellIcon as Bell,
    BellSlashIcon as BellOff,
    BookOpenIcon as BookOpen,
    RobotIcon as Bot,
    CubeIcon as Box,
    BriefcaseIcon as Briefcase,
    BuildingIcon as Building,
    BuildingsIcon as Building2,
    CalculatorIcon as Calculator,
    CalendarBlankIcon as Calendar,
    CalendarCheckIcon as CalendarCheck,
    CalendarDotsIcon as CalendarClock,
    CalendarDotsIcon as CalendarRange,
    CameraIcon as Camera,
    CheckIcon as Check,
    ChecksIcon as CheckCheck,
    CheckCircleIcon as CheckCircle,
    CheckCircleIcon as CheckCircle2,
    CheckSquareIcon as CheckSquare,
    CaretDownIcon as ChevronDown,
    CaretLeftIcon as ChevronLeft,
    CaretRightIcon as ChevronRight,
    CaretUpDownIcon as ChevronsUpDown,
    CaretUpIcon as ChevronUp,
    CircleIcon as Circle,
    ClipboardTextIcon as ClipboardCheck,
    ClipboardTextIcon as ClipboardList,
    ClockIcon as Clock,
    ClockIcon as Clock3,
    CloudIcon as Cloud,
    CopyIcon as Copy,
    ArrowElbowDownLeftIcon as CornerDownLeft,
    CpuIcon as Cpu,
    CreditCardIcon as CreditCard,
    CrosshairIcon as Crosshair,
    DatabaseIcon as Database,
    CurrencyDollarIcon as DollarSign,
    DoorIcon as DoorClosed,
    DoorOpenIcon as DoorOpen,
    DownloadSimpleIcon as Download,
    DropIcon as Droplet,
    PencilSimpleIcon as Edit2,
    PencilSimpleLineIcon as Edit3,
    ArrowSquareOutIcon as ExternalLink,
    EyeIcon as Eye,
    EyeSlashIcon as EyeOff,
    FactoryIcon as Factory,
    FileZipIcon as FileArchive,
    FileTextIcon as FileCheck,
    FileTextIcon as FileCheck2,
    FileCodeIcon as FileCode,
    FileArrowDownIcon as FileDown,
    FilePlusIcon as FilePlus2,
    SignatureIcon as FileSignature,
    FileXlsIcon as FileSpreadsheet,
    FileTextIcon as FileText,
    FilmStripIcon as Film,
    FunnelIcon as Filter,
    FlagIcon as Flag,
    FlameIcon as Flame,
    GaugeIcon as Gauge,
    DiamondIcon as Gem,
    GitDiffIcon as GitCompare,
    FrameCornersIcon as GlassWater,
    DotsSixVerticalIcon as GripVertical,
    HardDriveIcon as HardDrive,
    HardHatIcon as HardHat,
    HashIcon as Hash,
    QuestionIcon as HelpCircle,
    ClockCounterClockwiseIcon as History,
    HourglassIcon as Hourglass,
    ImageIcon as Image,
    ImageBrokenIcon as ImageOff,
    ImagesIcon as Images,
    TrayIcon as Inbox,
    InfoIcon as Info,
    KanbanIcon as Kanban,
    BankIcon as Landmark,
    StackIcon as Layers,
    SquaresFourIcon as LayoutDashboard,
    SquaresFourIcon as LayoutGrid,
    ListDashesIcon as LayoutList,
    LightbulbIcon as Lightbulb,
    LinkSimpleIcon as Link2,
    ListIcon as List,
    ListChecksIcon as ListChecks,
    ListPlusIcon as ListPlus,
    TreeStructureIcon as ListTree,
    CircleNotchIcon as Loader2,
    LockIcon as Lock,
    SignInIcon as LogIn,
    SignOutIcon as LogOut,
    EnvelopeIcon as Mail,
    MapPinIcon as MapPin,
    ListIcon as Menu,
    ChatCircleIcon as MessageCircle,
    ChatTextIcon as MessageSquare,
    MinusIcon as Minus,
    DotsThreeVerticalIcon as MoreVertical,
    NotebookIcon as NotebookPen,
    PackageIcon as Package,
    PackageIcon as Package2,
    PackageIcon as PackageCheck,
    PackageIcon as PackagePlus,
    PackageIcon as PackageSearch,
    BrowserIcon as PanelTop,
    PauseIcon as Pause,
    PauseCircleIcon as PauseCircle,
    PencilSimpleIcon as Pencil,
    PencilRulerIcon as PencilRuler,
    PencilLineIcon as PenLine,
    PenNibIcon as PenTool,
    PercentIcon as Percent,
    PhoneIcon as Phone,
    PhoneCallIcon as PhoneCall,
    PhoneXIcon as PhoneMissed,
    PlayIcon as Play,
    PlusIcon as Plus,
    PlusCircleIcon as PlusCircle,
    PrinterIcon as Printer,
    QrCodeIcon as QrCode,
    ReceiptIcon as Receipt,
    ArrowsClockwiseIcon as RefreshCw,
    SwapIcon as Replace,
    ArrowCounterClockwiseIcon as RotateCcw,
    ArrowClockwiseIcon as RotateCw,
    PathIcon as Route,
    RulerIcon as Ruler,
    FloppyDiskIcon as Save,
    ScalesIcon as Scale,
    ScanIcon as ScanEye,
    ScissorsIcon as Scissors,
    MagnifyingGlassIcon as Search,
    PaperPlaneTiltIcon as Send,
    GearSixIcon as Settings,
    ShieldIcon as Shield,
    ShieldWarningIcon as ShieldAlert,
    ShieldCheckIcon as ShieldCheck,
    ShoppingCartIcon as ShoppingCart,
    SlidersIcon as Sliders,
    SlidersHorizontalIcon as SlidersHorizontal,
    SnowflakeIcon as Snowflake,
    SparkleIcon as Sparkles,
    SquareIcon as Square,
    StarIcon as Star,
    NoteIcon as StickyNote,
    TableIcon as TableGrid,
    TagIcon as Tag,
    TargetIcon as Target,
    TimerIcon as Timer,
    TrashIcon as Trash2,
    TrendDownIcon as TrendingDown,
    TrendUpIcon as TrendingUp,
    WarningIcon as TriangleAlert,
    TrophyIcon as Trophy,
    TruckIcon as Truck,
    ArrowUUpLeftIcon as Undo2,
    UploadSimpleIcon as Upload,
    CloudArrowUpIcon as UploadCloud,
    UserIcon as User,
    UserCheckIcon as UserCheck,
    UserCircleIcon as UserCircle,
    UserPlusIcon as UserPlus,
    UsersIcon as Users,
    UserMinusIcon as UserX,
    WalletIcon as Wallet,
    MagicWandIcon as Wand2,
    WarehouseIcon as Warehouse,
    WifiHighIcon as Wifi,
    WifiSlashIcon as WifiOff,
    WrenchIcon as Wrench,
    XIcon as X,
    XCircleIcon as XCircle,
    LightningIcon as Zap,
    MagnifyingGlassPlusIcon as ZoomIn,
};
